### ISSUE TITLE
Install dependencies

### ISSUE THREAD

**Issue by shadowphiar** [mborik/SAA1099Tracker#3]
Hi,
(Sorry for the newbie question - I mostly work in c++ and don't do a lot of user interface coding.)

I've downloaded the source, with a view towards possibly having a go at some file import/export functions. I have run 'npm install' and 'bower install' - are these the correct steps and sufficient? Unfortunately I get errors when I try to build with 'grunt':

```
Running "less:styles" (less) task
>> NameError: variable @dl-horizontal-breakpoint is undefined in bower_components/bootstrap/less/type.less on line 214, column 22:
>> 213 
>> 214   @media (min-width: @dl-horizontal-breakpoint) {
>> 215     dt {
Warning: Error compiling styles/bootstrap.less Use --force to continue.

Aborted due to warnings.
```

Have I got an appropriate version of the dependencies?

Alternatively, the ReadMe mentions you use IDE from Cloud9 - do you have a workspace there that I could just clone?

**Comment by mborik** [comment]
Sorry for delayed answer, I was on conference abroad and then on vacation. Your issue with running grunt on project was caused by newer version of bootstrap library downloaded by Bower. Issue was that I use my own `variables.less` and newer version of bootstrap added another required predefined variable into its own default variables.
