### ISSUE TITLE
BUG: Export native STMF exports JSON file

### ISSUE THREAD

**Issue by ffilipus** [mborik/SAA1099Tracker#35]
### 🐛 Describe the bug
Exported STMF file is not binary, but JSON file with title, author, samples, etc. fields.

### 🕹 Steps to reproduce the behavior
1. Go to https://saa1099tracker.borik.net/
2. Load demosong, i.e. Orava II
3. Export to native STMF format and save file
4. View saved file - it's JSON file.

### 🤖 Expected behavior
Saved STMF is binary file described in Help > Export data format.

### 🖥 Desktop
 - **Browser:** Chrome 108.0.5359.125
 - **Version:** 2.0.4

**Comment by mborik** [comment]
Hi @ffilipus , it's just misunderstanding between native tracker format and "Binary compilation" (see Export menu) format.
- Nativne format for tracker is JSON-based, because it's easiest way for JavaScript to handle to "snapshot" of musician's workspace.
- Binary compilation is highly optimized and memory effective binary format that Player could interpret and fill the SAA1099 registers on 8bit platforms.

Sure, that binary format starting with control string "STMF", but it's pretty common for all binary module formats to "sign" itself. Player also checks that string during initialization.
