### ISSUE TITLE
Chrome: closing tab during playback loops playback buffer

### ISSUE THREAD

**Issue by stefandrissen** [mborik/SAA1099Tracker#5]
Using Chrome 56 on Windows 10.

1. import any demo song
2. start playback
3. close tab

-> the "Do you want to leave this site? Changes you made may not be saved." dialog pops up and playback loops on the contents of the playback buffer.

Update of handling on other browsers:

Edge: wow! - playback and tracker continue in background
Firefox: nice - playback continues, tracker does not
Internet Explorer: I can't even start... :-)

**Comment by mborik** [comment]
You forgot to note on which environment you've tested (I mean, deployed on my webpage or your custom build?) and which version, because now, version 1.2.0 is in release candidate status and it's completely reworked and bugfixed...
But it doesn't matter because behavior of the `onbeforeunload` and its "freezing" of WebAudio or canvas rendering while OS displayed the dialog and waits to user's action, it's in his regime. Only way I could affect this behavior is to call the Stop method just before the system dialog was shown - should be implemented and released with v1.2.0.

_...and final note: In [README](https://github.com/mborik/SAA1099Tracker/blob/master/README.md) I don't mention any of Microsoft's browser and therefore it was unsupported and probably I'll never support them in future..._

**Comment by stefandrissen** [comment]
The version deployed on your web page which is 1.1.8 - the massive rework remark triggered me to have another look. But I see now that the version on your web page is not the latest.

And as to browser support, fair enough, interesting that the browser that works best is not in the compatibility list. ;-)

**Comment by mborik** [comment]
fixed with 9e98b6c276b5e9d8b4901bd0eca02880a771f790, deployed in forthcoming release; issue closed
