### ISSUE TITLE
Firefox: pattern view broken

### ISSUE THREAD

**Issue by utz82** [mborik/SAA1099Tracker#8]
Pattern view only displays the edit highlight, but no actual content.
Firefox 62.0 on Gentoo Linux

![saatracker_display_bug](https://user-images.githubusercontent.com/5324866/64283805-6d56fd80-cf58-11e9-8137-95fbc1f1292b.png)

**Comment by mborik** [comment]
Hi, it is strange because now I'm test current public version on many FF versions (updates from 45, through 52, 60... to the latest 69) and everything runs silky smooth.
It could be some issue with your custom build of FF or graphics drivers in Gentoo. I don't know...

Is there any strange error messages in devtool console when you run tracker [in developer mode](https://saa1099tracker.borik.net/?dev)?

**Comment by utz82** [comment]
No error messages, but I did some investigation and the issue seems to be related with webgl initialization. After initializing webgl via another site (in this case, https://get.webgl.org/), the pattern view works as intended. Weird. Anything else I can try to track down this problem?

**Comment by mborik** [comment]
This tracker hasn't related to WebGL or any 3D requirements. It using just basic 2d context of HtmlCanvas. Sorry, I couldn't track problem of your custom build of browser in custom built distro. :wink:
